export {
  WebviewDebugPayloadSchema,
  WebviewSendRequestSchema,
  WebviewClearRequestSchema,
  WebviewDeleteChatRequestSchema,
  WebviewInsertCodeRequestSchema,
  WebviewAttachFileRequestSchema,
  WebviewPasteCheckRequestSchema,
  WebviewOpenResponseRequestSchema,
  WebviewSaveChatStateRequestSchema,
  WebviewFetchModelsRequestSchema,
  WebviewFetchAgentsRequestSchema,
  WebviewSetAgentRequestSchema,
  WebviewCancelRequestSchema,
  WebviewRevertLatestChangeRequestSchema,
  WebviewDebugRequestSchema,
  WebviewToExtensionMessageSchema,
  type WebviewDebugPayload,
  type WebviewSendRequest,
  type WebviewClearRequest,
  type WebviewDeleteChatRequest,
  type WebviewInsertCodeRequest,
  type WebviewAttachFileRequest,
  type WebviewPasteCheckRequest,
  type WebviewOpenResponseRequest,
  type WebviewSaveChatStateRequest,
  type WebviewFetchModelsRequest,
  type WebviewFetchAgentsRequest,
  type WebviewSetAgentRequest,
  type WebviewCancelRequest,
  type WebviewRevertLatestChangeRequest,
  type WebviewDebugRequest,
  type WebviewToExtensionMessage,
} from '../dto/webview/incoming';
export {
  ChangedFileSchema,
  TurnChangeSetSchema,
  ExtensionPasteResultMessageSchema,
  ExtensionCodeRefMessageSchema,
  ExtensionUserMessageSchema,
  ExtensionErrorMessageSchema,
  ExtensionStreamStartMessageSchema,
  ExtensionStreamModelMessageSchema,
  ExtensionStreamDeltaMessageSchema,
  ExtensionStreamFinalMessageSchema,
  ExtensionStreamEndMessageSchema,
  ExtensionToolEventMessageSchema,
  ExtensionAgentsLoadedMessageSchema,
  ExtensionModelsLoadedMessageSchema,
  ExtensionAgentChangedMessageSchema,
  ExtensionClearedMessageSchema,
  ExtensionApplyPromptMessageSchema,
  ExtensionRevertAppliedMessageSchema,
  ExtensionRevertInvalidMessageSchema,
  ExtensionToWebviewMessageSchema,
  type ChangedFileDto,
  type TurnChangeSetDto,
  type ExtensionPasteResultMessage,
  type ExtensionCodeRefMessage,
  type ExtensionUserMessage,
  type ExtensionErrorMessage,
  type ExtensionStreamStartMessage,
  type ExtensionStreamModelMessage,
  type ExtensionStreamDeltaMessage,
  type ExtensionStreamFinalMessage,
  type ExtensionStreamEndMessage,
  type ExtensionToolEventMessage,
  type ExtensionAgentsLoadedMessage,
  type ExtensionModelsLoadedMessage,
  type ExtensionAgentChangedMessage,
  type ExtensionClearedMessage,
  type ExtensionApplyPromptMessage,
  type ExtensionRevertAppliedMessage,
  type ExtensionRevertInvalidMessage,
  type ExtensionToWebviewMessage,
} from '../dto/webview/outgoing';
import {
  WebviewToExtensionMessageSchema,
  type WebviewToExtensionMessage,
} from '../dto/webview/incoming';
import {
  ExtensionToWebviewMessageSchema,
  type ExtensionToWebviewMessage,
} from '../dto/webview/outgoing';

export function parseWebviewToExtensionMessage(input: unknown): WebviewToExtensionMessage {
  return WebviewToExtensionMessageSchema.parse(input);
}

export function parseExtensionToWebviewMessage(input: unknown): ExtensionToWebviewMessage {
  return ExtensionToWebviewMessageSchema.parse(input);
}
